### ISSUE TITLE
I use this plugin to prompt autoupdate on Android platform.Got missing exec error

### ISSUE THREAD

**Issue by chuwenbo** [bitstadium/HockeySDK-Cordova#51]
I use this plugin to prompt autoupdate on  Android platform.
android version 5.1.1
cordova Versin 6.1.1

my code:
 function onDeviceReady() {
        hockeyapp.start(null,null,"my app ID")
        hockeyapp.checkForUpdate();
}

error message:
missing exec:HockeyApp.start
missing exec:HockeyApp.checkForUpdate

Is there something wrong?

**Comment by lostintangent** [comment]
@chuwenbo Are you running your app in Ripple? The "missing exec" error is typically caused by the fact that you're running the app in an environment where a plugin's native code isn't available (e.g. a browser). Could you try running your app in the Android emulator and/or a device and see if that works for you?

**Comment by chuwenbo** [comment]
@lostintangent  Has the same problem in the android device.

**Comment by lostintangent** [comment]
Could you try removing and re-adding the plugin? It's possible that the installation had some issues, and the native code didn't get successfully setup. We haven't been able to repro this unfortunately, so I'm just curious if it would make a difference doing a clean install.

**Comment by TroubleMakerBen** [comment]
I'll close this as this is rather old and we haven't heard back. Let us know if you run into this again. =)
