### ISSUE TITLE
App crashes during startup sometimes

### ISSUE THREAD

**Issue by badass-icon** [bitstadium/HockeySDK-Cordova#54]
Hi!

We are trying to use HockeySDK-Cordova for our cordova project using the following code:

```
      ionic.Platform.ready(function () {
        if (window.hockeyapp) {
          window.hockeyapp.start(null, null, "my_app_guid_here");
        }
      });
```

Unfortunately our app successfully starts only once per 4-5 tries, other times it's frozen and don't react on touches/keypresses, debugger window also gets frozen.

I believe something wrong happens inside the native part of plugin, because the following code gets called, and after that it stops responding:

```
exec(success, failure, "HockeyApp", "start", [appId, loginMode, appSecret, autoSend, ignoreDefaultHandler]);
```

Do you have any clue why that may happen?

P.S.
It starts and works with no problems when `window.hockeyapp.start` is commented (disabled)

We are using Cordova 6.0.0 and iPad Air 2 with iOS 9.3, but situation the same for any device in simulator as well.

Reproducing scenario:
1) Start app
2) Press the home button 2 times and close app.
3) Try to start app again. (if it works - go to point 2)

**Comment by ruzhovt** [comment]
I've debugged `plugins/cordova-plugin-hockeyapp/src/ios/HockeyApp.m` file and noticed that `(void) start:(CDVInvokedUrlCommand*)command` is sometimes even not called, however `exec(success, failure, "HockeyApp", "start", [appId, loginMode, appSecret, autoSend, ignoreDefaultHandler]);` is always executed.

**Comment by paya-cz** [comment]
@badass-icon what was the problem? I am having the same problem

**Comment by paya-cz** [comment]
Hello,

I was using a code that looked like:

declare var hockeyapp: any;

and then used that in my ionic app. I have no idea what error was thrown, because when i called hockeyapp.start, the screen just went white with only green battery icon visible. I didn't find any useful information when running in iOS simulator either. However, I switched to this package:

https://github.com/hicsail/ionic-hockeyapp

And I used it instead of directly accessing hockeyapp, and that fixed the issue I was having and now everything works fine.

**Comment by TroubleMakerBen** [comment]
Hi @paya-cz,

thx for the update on this issue and I'm glad that you were able to figure it out with using the unofficial ionic package.

Thanks for using HockeyApp and please don't hesitate to get in touch in case you run into issues again.
