### ISSUE TITLE
Track events is not working

### ISSUE THREAD

**Issue by kigero** [bitstadium/HockeySDK-Cordova#79]
I'm calling into the hockeyapp API like this:

```
hockeyapp.start(null, null, 'my-id', true);
hockeyapp.trackEvent(null, null, 'OPENED');
```

I never see the event in the HockeyApp dashboard.  The session is recorded properly, and crashes make it OK, just the events are not showing up.  If I add a handler for the success and error callbacks, the success callback is called.  Any ideas why this is not working?

**Comment by TroubleMakerBen** [comment]
Hey @kigero,

Which platform are you targeting with your app, iOS or Android?

Best,
Benjamin

**Comment by bmourat** [comment]
Hi @kigero 

Are you using the latest version of HockeySDK-Cordova plugin? I've checked both on ios and android and this code work as expected. There is some delay between calling trackEvent method and events actually appearing on the portal, but that's normal. If this issue is still bothering you, can you please provide some details on your setup and platform you are testing on?

Best,
Murat

**Comment by kigero** [comment]
It looks like I've started to get events now - there just must be a longer delay than I was expecting before the events show up.  So it looks like this is working as expected, with the delay.

For the record, this was on the latest plugin version and on iOS.

Thanks!
